local actions, lastTrigger = {}, nil
native('DialogCreate', function() return {} end)
native('DialogAddButton', function() return {} end)
native('DialogAddQuitButton', function() return {} end)
native('CreateTrigger', function() lastTrigger = {}; return lastTrigger end)
native('TriggerAddAction', function(_, callback) actions[#actions + 1] = callback; return {} end)
for _, name in ipairs({'DialogSetMessage', 'DialogDisplay', 'DialogClear', 'DialogDestroy', 'DestroyTrigger',
    'TriggerRegisterDialogEvent'}) do
    native(name, function() end)
end
local clicked, clicker = nil, PLAYER_RAW
native('GetClickedButton', function() return clicked end)
native('GetTriggerPlayer', function() return clicker end)
local Dialog = require('wrappers.dialog')
local Player = require('wrappers.player')
eq(totalCalls(), 0)

-- Simulates Warcraft firing every dialog trigger for a click on the raw button `raw` by the raw player `who`.
local function click(raw, who)
    clicked, clicker = raw, who or PLAYER_RAW
    for _, action in ipairs(actions) do action() end
end

test('dialogs keep identity and forward exact natives', function()
    eq(Dialog.fromHandle(nil), nil)
    local d = Dialog.create()
    eq(Dialog.fromHandle(d.handle), d); eq(d:getHandle(), d.handle); eq(d:isDisposed(), false)
    d:setMessage('Choose'); expectCall('DialogSetMessage', d.handle, 'Choose')
    local p = Player.fromIndex(0)
    d:show(p); expectCall('DialogDisplay', p.handle, d.handle, true)
    d:hide(p); expectCall('DialogDisplay', p.handle, d.handle, false)
    fails(function() d:show(d) end, 'Dialog.show: expected Player wrapper')
    fails(function() d:hide(d) end, 'Dialog.hide: expected Player wrapper')
    eq(callCount('DialogDisplay'), 2)
    d:destroy()
end)

test('addButton accepts a callback, options, or options and a callback', function()
    local d = Dialog.create()
    local plain = d:addButton('Plain')
    expectCall('DialogAddButton', d.handle, 'Plain', 0)
    eq(plain:getDialog(), d); eq(plain:isDisposed(), false); eq(plain:getHandle(), plain.handle)
    d:addButton('Keyed', {hotkey = 's'}); expectCall('DialogAddButton', d.handle, 'Keyed', string.byte('S'))
    d:addButton('Digit', {hotkey = '7'}, function() end)
    expectCall('DialogAddButton', d.handle, 'Digit', string.byte('7'))
    d:addButton('Called', function() end); expectCall('DialogAddButton', d.handle, 'Called', 0)
    d:addButton('Quit', {quit = true}); expectCall('DialogAddQuitButton', d.handle, false, 'Quit', 0)
    d:addButton('Score', {quit = true, scoreScreen = true, hotkey = 'Q'})
    expectCall('DialogAddQuitButton', d.handle, true, 'Score', string.byte('Q'))
    d:destroy()
end)

test('the internal trigger is created once, and only for a callback', function()
    local d = Dialog.create()
    d:addButton('A'); d:addButton('B', {hotkey = 'B'})
    eq(callCount('CreateTrigger'), 0)
    d:addButton('C', function() end); d:addButton('D', nil, function() end)
    eq(callCount('CreateTrigger'), 1); eq(callCount('TriggerRegisterDialogEvent'), 1)
    eq(callCount('TriggerAddAction'), 1)
    expectCall('TriggerRegisterDialogEvent', lastTrigger, d.handle)
    local trigger = lastTrigger
    d:destroy(); expectCall('DestroyTrigger', trigger)
    local quiet = Dialog.create()
    quiet:destroy(); eq(callCount('DestroyTrigger'), 1)
end)

test('bad buttons fail before any native', function()
    local d = Dialog.create()
    resetCalls()
    fails(function() d:addButton('x', {hotkey = 'ab'}) end, "Dialog.addButton: option 'hotkey' expected one letter or digit")
    fails(function() d:addButton('x', {hotkey = '!'}) end, "option 'hotkey' expected one letter or digit")
    fails(function() d:addButton('x', {hotkey = ''}) end, "option 'hotkey' expected one letter or digit")
    fails(function() d:addButton('x', {hotkey = 5}) end, "option 'hotkey' expected a string")
    fails(function() d:addButton('x', {scoreScreen = true}) end, "Dialog.addButton: option 'scoreScreen' needs 'quit'")
    fails(function() d:addButton('x', {colour = 1}) end, "unknown option 'colour'")
    fails(function() d:addButton('x', nil, 5) end, 'Dialog.addButton: expected a callback function')
    fails(function() d:addButton('x', function() end, function() end) end, 'Dialog.addButton: a callback given twice')
    fails(function() d:addButton('x', 5) end, 'Dialog.addButton: expected an options table')
    eq(totalCalls(), 0)
    d:destroy()
end)

test('a click runs that button callback with the clicking player', function()
    local d = Dialog.create()
    local seen = {}
    local stay = d:addButton('Stay', function(player) seen[#seen + 1] = {'stay', player} end)
    local leave = d:addButton('Leave', {hotkey = 'L'}, function(player) seen[#seen + 1] = {'leave', player} end)
    local silent = d:addButton('Silent')
    local other = {}
    click(stay.handle); click(leave.handle, other); click(silent.handle); click({})
    eq(#seen, 2)
    eq(seen[1][1], 'stay'); eq(seen[1][2], Player.fromIndex(0))
    eq(seen[2][1], 'leave'); eq(seen[2][2], Player.fromHandle(other))
    d:destroy()
end)

test('a failing callback is printed and later clicks still run', function()
    local d = Dialog.create()
    local count = 0
    local bad = d:addButton('Bad', function() error('intentional button probe') end)
    local good = d:addButton('Good', function() count = count + 1 end)
    click(bad.handle); click(good.handle); click(bad.handle); click(good.handle)
    eq(count, 2); eq(#PRINTED, 2)
    assert(PRINTED[1]:find('[wrappers] Dialog button callback failed:', 1, true), PRINTED[1])
    assert(PRINTED[1]:find('intentional button probe', 1, true), PRINTED[1])
    d:destroy()
end)

test('clear and destroy dispose the buttons, so later clicks run nothing', function()
    local d = Dialog.create()
    local count = 0
    local first = d:addButton('First', function() count = count + 1 end)
    local firstRaw = first.handle
    d:clear()
    expectCall('DialogClear', d.handle)
    eq(first:isDisposed(), true); eq(first.handle, nil); eq(first:getDialog(), d)
    fails(function() first:getHandle() end, 'DialogButton is disposed')
    click(firstRaw); eq(count, 0)
    local second = d:addButton('Second', function() count = count + 10 end)
    eq(callCount('CreateTrigger'), 1)
    click(second.handle); eq(count, 10)
    local secondRaw, raw = second.handle, d.handle
    d:destroy(); d:destroy()
    eq(callCount('DialogDestroy'), 1); expectCall('DialogDestroy', raw)
    eq(second:isDisposed(), true); eq(d:isDisposed(), true); eq(d.handle, nil)
    click(secondRaw); eq(count, 10)
    checkDisposed(d, {'getHandle', 'setMessage', 'addButton', 'show', 'hide', 'clear'})
end)

test('a callback may hide, clear or destroy its own dialog', function()
    local d = Dialog.create()
    local p = Player.fromIndex(0)
    local after = 0
    local hide = d:addButton('Hide', function(player) d:hide(player) end)
    local clear = d:addButton('Clear', function() d:clear() end)
    local trigger, raw = lastTrigger, d.handle
    click(hide.handle); expectCall('DialogDisplay', p.handle, raw, false)
    click(clear.handle); eq(clear:isDisposed(), true); eq(hide:isDisposed(), true)
    local destroy = d:addButton('Destroy', function() d:destroy(); after = after + 1 end)
    click(destroy.handle)
    eq(after, 1); eq(d:isDisposed(), true); eq(destroy:isDisposed(), true)
    expectCall('DestroyTrigger', trigger); expectCall('DialogDestroy', raw)
    eq(#PRINTED, 0)
end)

test('buttons have no destroy or fromHandle, and getDialog checks its receiver', function()
    local d = Dialog.create()
    local b = d:addButton('B')
    eq(b.destroy, nil); eq(b.fromHandle, nil)
    fails(function() b.getDialog(d) end, 'DialogButton.getDialog: expected DialogButton wrapper')
    d:destroy()
end)

test('create and addButton fail clearly when the native returns nil', function()
    native('DialogCreate', function() return nil end)
    fails(function() Dialog.create() end, 'Dialog.create: native returned nil')
    native('DialogCreate', function() return {} end)
    local d = Dialog.create()
    native('DialogAddButton', function() return nil end)
    fails(function() d:addButton('x') end, 'Dialog.addButton: native returned nil')
    native('DialogAddButton', function() return {} end)
    d:destroy()
end)
