local Unit = require('wrappers.unit')
local PlayerWrapper = require('wrappers.player')
local Timer = require('wrappers.timer')
local Trigger = require('wrappers.trigger')
local Group = require('wrappers.group')
local Effect = require('wrappers.effect')
local Item = require('wrappers.item')
local Destructable = require('wrappers.destructable')
local Rect = require('wrappers.rect')
local Region = require('wrappers.region')
local Force = require('wrappers.force')

local unit = Unit.create(PlayerWrapper.fromIndex(0), 1751543663, 0, 0, 270)
unit:setPosition(1, 2)
unit:setLife(unit:getMaxLife())
local group = Group.create()
group:add(unit)
for _, member in ipairs(group:getUnits()) do member:setLife(100) end
local effect = Effect.attach('model.mdx', unit, 'origin')
effect:setScale(0.5)
local timer = Timer.create()
timer:start(1, false, function(self) self:pause(); self:destroy(); return 1 end)
local trigger = Trigger.create()
trigger:registerUnitEvent(unit, EVENT_UNIT_DEATH)
trigger:addAction(function(self) self:disable(); return 2 end)
---@type unit?
local maybeRaw = unit.handle
local maybe = Unit.fromHandle(maybeRaw)
if maybe then maybe:setLife(50) end
---@type nil
local absent = Unit.fromHandle(nil)
assert(absent == nil)
---@type MoonwellWrappers.Unit
local definite = assert(Unit.fromHandle(unit:getHandle()))
definite:kill()
local item = Item.create(1918989411, 0, 0)
item:setLife(item:getLife() + 1)
unit:issueTargetOrder('smart', item)
unit:damageTarget(item, 10, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS)
local slotItem = unit:getItemInSlot(0)
if slotItem then slotItem:setCharges(2) end
local tree = Destructable.create(1280601204, 0, 0, 270, 1, 0)
trigger:registerDeathEvent(tree)
local area = Rect.create(-100, -100, 100, 100)
local region = Region.create()
region:addRect(area)
trigger:registerEnterRegion(region)
local action = trigger:addAction(function(self) self:disable() end)
local condition = trigger:addCondition(function() return unit:isAlive() end)
trigger:removeAction(action)
trigger:removeCondition(condition)
group:enumInRect(area, function(member) return member:getTypeId() == unit:getTypeId() end)
group:forEach(function(member) member:setMana(0) end)
local force = Force.create()
force:add(PlayerWrapper.fromIndex(0))
for _, member in ipairs(force:getPlayers()) do member:addGold(10) end
force:destroy()
region:destroy()
area:destroy()
tree:remove()
item:remove()
effect:destroy()
group:destroy()
trigger:destroy()
unit:remove()
return true
