local Unit = require('wrappers.unit')
local PlayerWrapper = require('wrappers.player')
local Timer = require('wrappers.timer')
local Trigger = require('wrappers.trigger')
local Group = require('wrappers.group')
local Effect = require('wrappers.effect')
local Item = require('wrappers.item')
local Destructable = require('wrappers.destructable')
local Rect = require('wrappers.rect')
local Region = require('wrappers.region')
local Force = require('wrappers.force')
local TextTag = require('wrappers.texttag')
local Sound = require('wrappers.sound')
local Lightning = require('wrappers.lightning')
local Image = require('wrappers.image')
local Ubersplat = require('wrappers.ubersplat')
local FogModifier = require('wrappers.fogmodifier')
local Dialog = require('wrappers.dialog')
local Multiboard = require('wrappers.multiboard')
local Leaderboard = require('wrappers.leaderboard')
local Quest = require('wrappers.quest')
local DefeatCondition = require('wrappers.defeatcondition')
local TimerDialog = require('wrappers.timerdialog')
local Frame = require('wrappers.frame')

local unit = Unit.create(PlayerWrapper.fromIndex(0), 1751543663, 0, 0, 270)
unit:setPosition(1, 2)
unit:setLife(unit:getMaxLife())
unit:setVisible(unit:isVisible())
unit:setPaused(unit:isPaused())
unit:setPlayerColor(PLAYER_COLOR_RED)
unit:setColor(255, 255, 255, 255)
unit:setAbilityHidden(1097361000, false)
unit:setAbilityDisabled(1097361000, false, false)
if unit:setAbilityPermanent(1097361000, true) then print('permanent') end
local group = Group.create()
group:add(unit)
for _, member in ipairs(group:getUnits()) do member:setLife(100) end
local effect = Effect.attach('model.mdx', unit, 'origin')
effect:setScale(0.5)
local timer = Timer.create()
timer:start(1, false, function(self) self:pause(); self:destroy(); return 1 end)
local trigger = Trigger.create()
trigger:registerUnitEvent(unit, EVENT_UNIT_DEATH)
trigger:addAction(function(self) self:setEnabled(false); return 2 end)
---@type unit?
local maybeRaw = unit.handle
local maybe = Unit.fromHandle(maybeRaw)
if maybe then maybe:setLife(50) end
---@type nil
local absent = Unit.fromHandle(nil)
assert(absent == nil)
---@type MoonwellWrappers.Unit
local definite = assert(Unit.fromHandle(unit:getHandle()))
definite:kill()
local item = Item.create(1918989411, 0, 0)
item:setLife(item:getLife() + 1)
unit:issueTargetOrder('smart', item)
unit:damageTarget(item, 10, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS)
local slotItem = unit:getItemInSlot(0)
if slotItem then slotItem:setCharges(2) end
local tree = Destructable.create(1280601204, 0, 0, 270, 1, 0)
trigger:registerDeathEvent(tree)
local area = Rect.create(-100, -100, 100, 100)
local region = Region.create()
region:addRect(area)
trigger:registerEnterRegion(region)
local cancelAction = trigger:addAction(function(self) self:setEnabled(false) end)
local cancelCondition = trigger:addCondition(function() return unit:isAlive() end)
if unit:exists() and item:exists() and tree:exists() then print('present') end
local stopSweeping = Unit.autoDispose(0.5)
Unit.sweep()
stopSweeping()
Unit.autoDispose()()
cancelAction()
cancelCondition()
group:enumInRect(area, function(member) return member:getTypeId() == unit:getTypeId() end)
group:forEach(function(member) member:setMana(0) end)
local force = Force.create()
force:add(PlayerWrapper.fromIndex(0))
for _, member in ipairs(force:getPlayers()) do member:addGold(10) end
local tag = TextTag.create()
tag:setText('gate', 10)
tag:setPositionOnUnit(unit, 16)
tag:setVisibleFor(PlayerWrapper.fromIndex(0))
TextTag.float('+5', 0, 0, {size = 12, color = {255, 0, 0}, player = PlayerWrapper.fromIndex(0)})
local sound = Sound.create('war.flac', {is3D = true, fadeIn = 5})
sound:attachToUnit(unit)
sound:playFor(PlayerWrapper.fromIndex(0))
Sound.playOnce('war.flac', {volume = 100, x = 0, y = 0})
local bolt = Lightning.create('CLPB', 0, 0, 0, 100, 100, 0)
if bolt:move(0, 0, 0, 200, 200, 0, true) then bolt:setColor(1, 1, 1, 1) end
local image = Image.create('aoe.blp', 128, 128, 0, 0, 1)
image:setVisibleFor(PlayerWrapper.fromIndex(0))
local maybeImage = Image.fromHandle(image.handle)
if maybeImage then maybeImage:setPosition(10, 10) end
local splat = Ubersplat.create('HMED', 0, 0, {noBirthTime = true})
splat:finish()
local fog = FogModifier.rect(PlayerWrapper.fromIndex(0), FOG_OF_WAR_VISIBLE, area, true, false)
fog:start()
local chestEffect = Effect.attach('model.mdx', unit, 'chest')
chestEffect:setPlayerColor(PlayerWrapper.fromIndex(0))
chestEffect:playAnimation(ANIM_TYPE_ATTACK)
Effect.flashOn('model.mdx', unit, 'overhead')
Effect.flash('model.mdx', 0, 0)
for _, found in ipairs(Item.enumInRect(area, function(candidate) return candidate:getCharges() > 0 end)) do
    found:setCharges(1)
end
for _, found in ipairs(Destructable.enumInRect(area)) do found:kill() end
local dialog = Dialog.create()
dialog:setMessage('Choose')
local stay = dialog:addButton('Stay', function(player) player:addGold(10) end)
dialog:addButton('Leave', {hotkey = 'L', quit = true}, function(player) print(player:getName()) end)
if stay:getDialog() == dialog then dialog:show(PlayerWrapper.fromIndex(0)) end
local board = Multiboard.create(2, 2, 'Scores')
board:setCell(1, 1, {value = 'Name', color = {255, 204, 0}, showValue = true, showIcon = false})
board:setRow(2, {width = 0.05})
board:setAll({icon = 'x.blp'})
board:setVisibleFor(PlayerWrapper.fromIndex(0))
local leaders = Leaderboard.create('Kills')
leaders:addItem(PlayerWrapper.fromIndex(0), 'Red', 3)
leaders:setStyle({icons = false})
leaders:setItemStyle(PlayerWrapper.fromIndex(0), {value = true})
leaders:assign(PlayerWrapper.fromIndex(0))
local quest = Quest.create({title = 'Rescue', required = false})
local step = quest:addItem('Find the prince')
step:setCompleted(step:getQuest():isDiscovered())
local defeat = DefeatCondition.create('Lose the prince')
local countdown = TimerDialog.create(timer, 'Next wave')
countdown:setVisibleFor(PlayerWrapper.fromIndex(0))
countdown:destroy()
defeat:destroy()
quest:destroy()
leaders:destroy()
board:destroy()
dialog:destroy()
local gameUi = Frame.origin(ORIGIN_FRAME_GAME_UI)
local panel = Frame.create('EscMenuBackdrop', gameUi, {priority = 1})
panel:setAbsPoint(FRAMEPOINT_CENTER, 0.4, 0.3)
panel:setSize(0.3, 0.2)
local okButton = Frame.createByType('GLUETEXTBUTTON', panel, {name = 'Ok', inherits = 'ScriptDialogButton'})
okButton:setPoint(FRAMEPOINT_BOTTOM, panel, FRAMEPOINT_BOTTOM, 0, 0.02)
okButton:setText('OK')
okButton:setTextColor(255, 255, 255, 255)
local cancelOk = okButton:on(FRAMEEVENT_CONTROL_CLICK, function(player, event)
    okButton:releaseFocusFor(player)
    print(player:getName(), event.text, event.value, event.frame:getName())
end)
cancelOk()
okButton:setVisible(true)
okButton:setColor(255, 255, 255, 255)
Frame.setOriginHidden(false)
Frame.setAutoPosition(true)
panel:setVisibleFor(PlayerWrapper.fromIndex(0))
local maybeParent = okButton:getParent()
if maybeParent then maybeParent:setAlpha(255) end
panel:destroy()
chestEffect:destroy()
fog:destroy()
splat:destroy()
image:destroy()
bolt:destroy()
sound:destroy()
tag:destroy()
force:destroy()
region:destroy()
area:destroy()
tree:remove()
item:remove()
effect:destroy()
group:destroy()
trigger:destroy()
local Damage = require('wrappers.damage')
local Sync = require('wrappers.sync')
local stopDamaging = Damage.onDamaging(function(event)
    event:setAmount(event.amount * 2)
    event:setDamageType(DAMAGE_TYPE_UNIVERSAL)
    local source = event.source
    if source then print(source:getName(), event.target:getName()) end
end)
stopDamaging()
Damage.onDamaged(function(event) event:setAmount(event.amount + 1) end)()
local stopSynced = Sync.on('load', function(player, data) print(player:getName(), data) end)
stopSynced()
if Sync.send('load', 'code') then print('sent') end
print(unit:getCollisionSize())
unit:setPathing(true)
local Input = require('wrappers.input')
local WeatherEffect = require('wrappers.weathereffect')
local stopPressed = Input.onKeyDown(PlayerWrapper.fromIndex(0), OSKEY_Q, function(player, meta, repeated)
    if meta == METAKEY_SHIFT and not repeated then player:addGold(1) end
end, {repeats = true})
stopPressed()
Input.onKeyUp(PlayerWrapper.fromIndex(0), OSKEY_Q, function(player, meta) print(player:getName(), meta) end)()
local stopClicked = Input.onMouseDown(PlayerWrapper.fromIndex(0), function(player, x, y, button)
    if button == MOUSE_BUTTON_TYPE_LEFT then print(player:getName(), x + y) end
end)
stopClicked()
Input.onMouseUp(PlayerWrapper.fromIndex(0), function(_, x, y, button) print(x, y, button) end)()
Input.onMouseMove(PlayerWrapper.fromIndex(0), function(player, x, y) print(player:getId(), x, y) end)()
local weatherArea = Rect.create(-512, -512, 512, 512)
local rain = WeatherEffect.create(weatherArea, 1380018290)
rain:enable(true)
rain:enableFor(PlayerWrapper.fromIndex(0))
local maybeRain = WeatherEffect.fromHandle(rain.handle)
if maybeRain then maybeRain:enable(false) end
rain:destroy()
weatherArea:destroy()
local clap = Effect.abilityArt(1095267427, EFFECT_TYPE_CASTER)
if clap then Effect.flash(clap, 0, 0) end
local third = Effect.abilityArt(1095263859, EFFECT_TYPE_SPECIAL, 3)
if third then Effect.create(third, 0, 0):destroy() end
local events = Trigger.create()
events:registerPlayerStateEvent(PlayerWrapper.fromIndex(0), PLAYER_STATE_RESOURCE_GOLD, GREATER_THAN_OR_EQUAL, 1000)
events:registerPlayerAllianceChange(PlayerWrapper.fromIndex(0), ALLIANCE_SHARED_VISION)
events:registerGameStateEvent(GAME_STATE_TIME_OF_DAY, GREATER_THAN_OR_EQUAL, 18)
events:registerTimerExpireEvent(Timer.create())
events:addAction(function()
    local eventUnit, eventPlayer, eventItem = Unit.fromEvent(), PlayerWrapper.fromEvent(), Item.fromEvent()
    if eventUnit and eventPlayer and eventItem then
        print(eventUnit:getName(), eventPlayer:getName(), eventItem:getName())
    end
    local eventTree, eventTimer, eventRegion = Destructable.fromEvent(), Timer.fromEvent(), Region.fromEvent()
    if eventTree and eventTimer and eventRegion then
        print(eventTree:getName(), eventTimer:getTimeout(), eventRegion:containsPoint(0, 0))
    end
end)
events:destroy()
unit:remove()
return true
