local Unit = require('wrappers.unit')
local PlayerWrapper = require('wrappers.player')
local Timer = require('wrappers.timer')
local Trigger = require('wrappers.trigger')
local Group = require('wrappers.group')
local Effect = require('wrappers.effect')
local Item = require('wrappers.item')
local Destructable = require('wrappers.destructable')
local Rect = require('wrappers.rect')
local Region = require('wrappers.region')
local Force = require('wrappers.force')
local TextTag = require('wrappers.texttag')
local Sound = require('wrappers.sound')
local Lightning = require('wrappers.lightning')
local Image = require('wrappers.image')
local Ubersplat = require('wrappers.ubersplat')
local FogModifier = require('wrappers.fogmodifier')

local unit = Unit.create(PlayerWrapper.fromIndex(0), 1751543663, 0, 0, 270)
unit:setPosition(1, 2)
unit:setLife(unit:getMaxLife())
local group = Group.create()
group:add(unit)
for _, member in ipairs(group:getUnits()) do member:setLife(100) end
local effect = Effect.attach('model.mdx', unit, 'origin')
effect:setScale(0.5)
local timer = Timer.create()
timer:start(1, false, function(self) self:pause(); self:destroy(); return 1 end)
local trigger = Trigger.create()
trigger:registerUnitEvent(unit, EVENT_UNIT_DEATH)
trigger:addAction(function(self) self:disable(); return 2 end)
---@type unit?
local maybeRaw = unit.handle
local maybe = Unit.fromHandle(maybeRaw)
if maybe then maybe:setLife(50) end
---@type nil
local absent = Unit.fromHandle(nil)
assert(absent == nil)
---@type MoonwellWrappers.Unit
local definite = assert(Unit.fromHandle(unit:getHandle()))
definite:kill()
local item = Item.create(1918989411, 0, 0)
item:setLife(item:getLife() + 1)
unit:issueTargetOrder('smart', item)
unit:damageTarget(item, 10, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS)
local slotItem = unit:getItemInSlot(0)
if slotItem then slotItem:setCharges(2) end
local tree = Destructable.create(1280601204, 0, 0, 270, 1, 0)
trigger:registerDeathEvent(tree)
local area = Rect.create(-100, -100, 100, 100)
local region = Region.create()
region:addRect(area)
trigger:registerEnterRegion(region)
local action = trigger:addAction(function(self) self:disable() end)
local condition = trigger:addCondition(function() return unit:isAlive() end)
trigger:removeAction(action)
trigger:removeCondition(condition)
group:enumInRect(area, function(member) return member:getTypeId() == unit:getTypeId() end)
group:forEach(function(member) member:setMana(0) end)
local force = Force.create()
force:add(PlayerWrapper.fromIndex(0))
for _, member in ipairs(force:getPlayers()) do member:addGold(10) end
local tag = TextTag.create()
tag:setText('gate', 10)
tag:setPositionOnUnit(unit, 16)
tag:setVisibleFor(PlayerWrapper.fromIndex(0))
TextTag.float('+5', 0, 0, {size = 12, color = {255, 0, 0}, player = PlayerWrapper.fromIndex(0)})
local sound = Sound.create('war.flac', {is3D = true, fadeIn = 5})
sound:attachToUnit(unit)
sound:playFor(PlayerWrapper.fromIndex(0))
Sound.playOnce('war.flac', {volume = 100, x = 0, y = 0})
local bolt = Lightning.create('CLPB', 0, 0, 0, 100, 100, 0)
if bolt:move(0, 0, 0, 200, 200, 0, true) then bolt:setColor(1, 1, 1, 1) end
local image = Image.create('aoe.blp', 128, 128, 0, 0, 1)
image:setVisibleFor(PlayerWrapper.fromIndex(0))
local maybeImage = Image.fromHandle(image.handle)
if maybeImage then maybeImage:setPosition(10, 10) end
local splat = Ubersplat.create('HMED', 0, 0, {noBirthTime = true})
splat:finish()
local fog = FogModifier.rect(PlayerWrapper.fromIndex(0), FOG_OF_WAR_VISIBLE, area, true, false)
fog:start()
local itemEffect = Effect.attach('model.mdx', item, 'origin')
itemEffect:setPlayerColor(PlayerWrapper.fromIndex(0))
itemEffect:playAnimation(ANIM_TYPE_ATTACK)
Effect.flashOn('model.mdx', tree, 'origin')
Effect.flash('model.mdx', 0, 0)
for _, found in ipairs(Item.enumInRect(area, function(candidate) return candidate:getCharges() > 0 end)) do
    found:setCharges(1)
end
for _, found in ipairs(Destructable.enumInRect(area)) do found:kill() end
itemEffect:destroy()
fog:destroy()
splat:destroy()
image:destroy()
bolt:destroy()
sound:destroy()
tag:destroy()
force:destroy()
region:destroy()
area:destroy()
tree:remove()
item:remove()
effect:destroy()
group:destroy()
trigger:destroy()
unit:remove()
return true
