native('AddSpecialEffect', function() return {} end)
native('AddSpecialEffectTarget', function() return {} end)
native('DestroyEffect', function() end)
local Effect = require('wrappers.effect')
local Unit = require('wrappers.unit')
eq(totalCalls(), 0)

test('effect creation, attachment, transforms and non-owning disposal', function()
    local e, u = Effect.create('model.mdx', 10, 20), Unit.fromHandle({})
    expectCall('AddSpecialEffect', 'model.mdx', 10, 20)
    eq(Effect.fromHandle(nil), nil); eq(Effect.fromHandle(e.handle), e)
    local attached = Effect.attach('model.mdx', u, 'origin')
    expectCall('AddSpecialEffectTarget', 'model.mdx', u.handle, 'origin')
    native('BlzSetSpecialEffectPosition', function() end)
    native('BlzSetSpecialEffectScale', function() end)
    e:setPosition(1, 2, 3); expectCall('BlzSetSpecialEffectPosition', e.handle, 1, 2, 3)
    e:setScale(0.5); expectCall('BlzSetSpecialEffectScale', e.handle, 0.5)
    local raw = e:getHandle(); e:destroy(); e:destroy()
    expectCall('DestroyEffect', raw); eq(callCount('DestroyEffect'), 1); eq(e.handle, nil)
    for _, method in ipairs({'getHandle', 'setPosition', 'setScale'}) do
        fails(function() e[method](e) end, 'disposed')
    end
    attached:destroy(); eq(callCount('RemoveUnit'), 0); u:remove()
end)

test('invalid targets and nil native results fail clearly', function()
    fails(function() Effect.attach('model', {}, 'origin') end, 'Unit')
    local u = Unit.fromHandle({}); u:remove()
    fails(function() Effect.attach('model', u, 'origin') end, 'disposed')
    eq(callCount('AddSpecialEffectTarget'), 0)
    native('AddSpecialEffect', function() return nil end)
    fails(function() Effect.create('model', 0, 0) end, 'Effect.create')
    native('AddSpecialEffectTarget', function() return nil end)
    local live = Unit.fromHandle({})
    fails(function() Effect.attach('model', live, 'origin') end, 'Effect.attach')
    live:remove()
end)
