native('AddSpecialEffect', function() return {} end)
native('AddSpecialEffectTarget', function() return {} end)
native('DestroyEffect', function() end)
local Effect = require('wrappers.effect')
local Unit = require('wrappers.unit')
local Item = require('wrappers.item')
local Player = require('wrappers.player')
eq(totalCalls(), 0)

test('effect creation, attachment, transforms and non-owning disposal', function()
    local e, u = Effect.create('model.mdx', 10, 20), Unit.fromHandle({})
    expectCall('AddSpecialEffect', 'model.mdx', 10, 20)
    eq(Effect.fromHandle(nil), nil); eq(Effect.fromHandle(e.handle), e)
    local attached = Effect.attach('model.mdx', u, 'origin')
    expectCall('AddSpecialEffectTarget', 'model.mdx', u.handle, 'origin')
    native('BlzSetSpecialEffectPosition', function() end)
    native('BlzSetSpecialEffectScale', function() end)
    e:setPosition(1, 2, 3); expectCall('BlzSetSpecialEffectPosition', e.handle, 1, 2, 3)
    e:setScale(0.5); expectCall('BlzSetSpecialEffectScale', e.handle, 0.5)
    local raw = e:getHandle(); e:destroy(); e:destroy()
    expectCall('DestroyEffect', raw); eq(callCount('DestroyEffect'), 1); eq(e.handle, nil)
    for _, method in ipairs({'getHandle', 'setPosition', 'setScale'}) do
        failsAt(function() e[method](e) end, 'disposed')
    end
    attached:destroy(); eq(callCount('RemoveUnit'), 0); u:remove()
end)

test('invalid targets and nil native results fail clearly', function()
    failsAt(function() Effect.attach('model', {}, 'origin') end, 'Effect.attach: expected Widget wrapper')
    local u = Unit.fromHandle({}); u:remove()
    failsAt(function() Effect.attach('model', u, 'origin') end, 'disposed')
    eq(callCount('AddSpecialEffectTarget'), 0)
    native('AddSpecialEffect', function() return nil end)
    failsAt(function() Effect.create('model', 0, 0) end, 'Effect.create')
    native('AddSpecialEffectTarget', function() return nil end)
    local live = Unit.fromHandle({})
    failsAt(function() Effect.attach('model', live, 'origin') end, 'Effect.attach')
    live:remove()
    native('AddSpecialEffect', function() return {} end)
    native('AddSpecialEffectTarget', function() return {} end)
end)

test('effects attach to any widget', function()
    native('RemoveItem', function() end)
    local item = Item.fromHandle({})
    local e = Effect.attach('model.mdx', item, 'origin')
    expectCall('AddSpecialEffectTarget', 'model.mdx', item.handle, 'origin')
    e:destroy(); item:remove()
    failsAt(function() Effect.attach('model.mdx', item, 'origin') end, 'Effect.attach: Item is disposed')
    eq(callCount('AddSpecialEffectTarget'), 1)
end)

test('effect presentation setters forward exact arguments', function()
    local e, attack = Effect.create('model.mdx', 0, 0), {}
    checkSetters(e, {{'BlzSetSpecialEffectColor', 'setColor', 255, 0, 0}, {'BlzSetSpecialEffectAlpha', 'setAlpha', 128},
        {'BlzSetSpecialEffectTimeScale', 'setTimeScale', 0.5}, {'BlzSetSpecialEffectHeight', 'setHeight', 50},
        {'BlzSetSpecialEffectZ', 'setZ', 60}, {'BlzPlaySpecialEffect', 'playAnimation', attack}})
    native('BlzSetSpecialEffectColorByPlayer', function() end)
    e:setPlayerColor(Player.fromIndex(0)); expectCall('BlzSetSpecialEffectColorByPlayer', e.handle, PLAYER_RAW)
    failsAt(function() e:setPlayerColor(e) end, 'Effect.setPlayerColor: expected Player wrapper')
    eq(callCount('BlzSetSpecialEffectColorByPlayer'), 1)
    e:destroy()
    checkDisposed(e, {'setColor', 'setAlpha', 'setPlayerColor', 'setTimeScale', 'setOrientation', 'setHeight', 'setZ',
        'playAnimation'})
end)

test('setColor tints, and sets the alpha only when it is given one', function()
    local e = Effect.create('model.mdx', 0, 0)
    native('BlzSetSpecialEffectColor', function() end)
    native('BlzSetSpecialEffectAlpha', function() end)
    resetCalls()
    e:setColor(1, 2, 3); expectCall('BlzSetSpecialEffectColor', e.handle, 1, 2, 3)
    eq(callCount('BlzSetSpecialEffectAlpha'), 0)
    e:setColor(4, 5, 6, 0); expectCall('BlzSetSpecialEffectColor', e.handle, 4, 5, 6)
    expectCall('BlzSetSpecialEffectAlpha', e.handle, 0); eq(callCount('BlzSetSpecialEffectAlpha'), 1)
    eq(callName(totalCalls()), 'BlzSetSpecialEffectAlpha')
    e:destroy()
end)

test('setOrientation takes degrees and passes radians', function()
    local e = Effect.create('model.mdx', 0, 0)
    native('BlzSetSpecialEffectOrientation', function() end)
    e:setOrientation(180, 90, 0); expectCall('BlzSetSpecialEffectOrientation', e.handle, math.pi, math.pi / 2, 0)
    e:setOrientation(-45, 360, 30)
    expectCall('BlzSetSpecialEffectOrientation', e.handle, math.rad(-45), math.rad(360), math.rad(30))
    resetCalls()
    failsAt(function() e:setOrientation(nil, 0, 0) end, 'Effect.setOrientation: expected a finite yaw')
    failsAt(function() e:setOrientation(0, '90', 0) end, 'Effect.setOrientation: expected a finite pitch')
    failsAt(function() e:setOrientation(0, 0, math.huge) end, 'Effect.setOrientation: expected a finite roll')
    eq(totalCalls(), 0)
    e:destroy()
end)

test('flash creates and destroys at once without a wrapper', function()
    local raw = {}
    native('AddSpecialEffect', function() return raw end)
    eq(Effect.flash('boom.mdx', 1, 2), nil)
    eq(callName(1), 'AddSpecialEffect'); eq(callName(2), 'DestroyEffect'); eq(totalCalls(), 2)
    expectCall('AddSpecialEffect', 'boom.mdx', 1, 2); expectCall('DestroyEffect', raw)
    local u = Unit.fromHandle({})
    native('AddSpecialEffectTarget', function() return raw end)
    eq(Effect.flashOn('boom.mdx', u, 'chest'), nil)
    expectCall('AddSpecialEffectTarget', 'boom.mdx', u.handle, 'chest'); eq(callCount('DestroyEffect'), 2)
    native('AddSpecialEffect', function() return nil end)
    failsAt(function() Effect.flash('m', 0, 0) end, 'Effect.flash')
    native('AddSpecialEffectTarget', function() return nil end)
    failsAt(function() Effect.flashOn('m', u, 'origin') end, 'Effect.flashOn')
    failsAt(function() Effect.flashOn('m', {}, 'origin') end, 'Effect.flashOn: expected Widget wrapper')
    eq(callCount('DestroyEffect'), 2)
    native('AddSpecialEffect', function() return {} end)
    native('AddSpecialEffectTarget', function() return {} end)
    u:remove()
end)

test('abilityArt reads one entry of the art list, and nil for none', function()
    local caster, art = {}, {'first.mdl', 'second.mdl'}
    native('GetAbilityEffectById', function(_, _, index) return art[index + 1] or '' end)
    eq(Effect.abilityArt(1095267427, caster), 'first.mdl'); expectCall('GetAbilityEffectById', 1095267427, caster, 0)
    eq(Effect.abilityArt(1095267427, caster, 2), 'second.mdl')
    expectCall('GetAbilityEffectById', 1095267427, caster, 1)
    eq(Effect.abilityArt(1095267427, caster, 2.0), 'second.mdl')
    eq(Effect.abilityArt(1095267427, caster, 3), nil)
    native('GetAbilityEffectById', function() return nil end)
    eq(Effect.abilityArt(1095267427, caster), nil)
    resetCalls()
    for _, bad in ipairs({0, -1, 1.5, '1', 0/0, 2^31, math.huge, {}}) do
        failsAt(function() Effect.abilityArt(1095267427, caster, bad) end,
            'Effect.abilityArt: expected an integer index of at least 1')
    end
    eq(totalCalls(), 0)
end)

test('a model that is not a string fails at the caller, before any native', function()
    local u = Unit.fromHandle({})
    for _, bad in ipairs({false, 7, {}}) do
        failsAt(function() Effect.create(bad, 0, 0) end, 'Effect.create: expected a model path')
        failsAt(function() Effect.attach(bad, u, 'origin') end, 'Effect.attach: expected a model path')
        failsAt(function() Effect.flash(bad, 0, 0) end, 'Effect.flash: expected a model path')
        failsAt(function() Effect.flashOn(bad, u, 'origin') end, 'Effect.flashOn: expected a model path')
    end
    failsAt(function() Effect.create(nil, 0, 0) end, 'Effect.create: expected a model path')
    failsAt(function() Effect.flash(Effect.abilityArt(1, {}), 0, 0) end, 'Effect.flash: expected a model path')
    eq(callCount('AddSpecialEffect'), 0); eq(callCount('AddSpecialEffectTarget'), 0)
    Effect.create('', 0, 0):destroy(); expectCall('AddSpecialEffect', '', 0, 0)
    u:remove()
end)
