native('AddSpecialEffect', function() return {} end)
native('AddSpecialEffectTarget', function() return {} end)
native('DestroyEffect', function() end)
local Effect = require('wrappers.effect')
local Unit = require('wrappers.unit')
local Item = require('wrappers.item')
local Player = require('wrappers.player')
eq(totalCalls(), 0)

test('effect creation, attachment, transforms and non-owning disposal', function()
    local e, u = Effect.create('model.mdx', 10, 20), Unit.fromHandle({})
    expectCall('AddSpecialEffect', 'model.mdx', 10, 20)
    eq(Effect.fromHandle(nil), nil); eq(Effect.fromHandle(e.handle), e)
    local attached = Effect.attach('model.mdx', u, 'origin')
    expectCall('AddSpecialEffectTarget', 'model.mdx', u.handle, 'origin')
    native('BlzSetSpecialEffectPosition', function() end)
    native('BlzSetSpecialEffectScale', function() end)
    e:setPosition(1, 2, 3); expectCall('BlzSetSpecialEffectPosition', e.handle, 1, 2, 3)
    e:setScale(0.5); expectCall('BlzSetSpecialEffectScale', e.handle, 0.5)
    local raw = e:getHandle(); e:destroy(); e:destroy()
    expectCall('DestroyEffect', raw); eq(callCount('DestroyEffect'), 1); eq(e.handle, nil)
    for _, method in ipairs({'getHandle', 'setPosition', 'setScale'}) do
        fails(function() e[method](e) end, 'disposed')
    end
    attached:destroy(); eq(callCount('RemoveUnit'), 0); u:remove()
end)

test('invalid targets and nil native results fail clearly', function()
    fails(function() Effect.attach('model', {}, 'origin') end, 'Effect.attach: expected Widget wrapper')
    local u = Unit.fromHandle({}); u:remove()
    fails(function() Effect.attach('model', u, 'origin') end, 'disposed')
    eq(callCount('AddSpecialEffectTarget'), 0)
    native('AddSpecialEffect', function() return nil end)
    fails(function() Effect.create('model', 0, 0) end, 'Effect.create')
    native('AddSpecialEffectTarget', function() return nil end)
    local live = Unit.fromHandle({})
    fails(function() Effect.attach('model', live, 'origin') end, 'Effect.attach')
    live:remove()
    native('AddSpecialEffect', function() return {} end)
    native('AddSpecialEffectTarget', function() return {} end)
end)

test('effects attach to any widget', function()
    native('RemoveItem', function() end)
    local item = Item.fromHandle({})
    local e = Effect.attach('model.mdx', item, 'origin')
    expectCall('AddSpecialEffectTarget', 'model.mdx', item.handle, 'origin')
    e:destroy(); item:remove()
    fails(function() Effect.attach('model.mdx', item, 'origin') end, 'Effect.attach: Item is disposed')
    eq(callCount('AddSpecialEffectTarget'), 1)
end)

test('effect presentation setters forward exact arguments', function()
    local e, attack = Effect.create('model.mdx', 0, 0), {}
    checkSetters(e, {{'BlzSetSpecialEffectColor', 'setColor', 255, 0, 0}, {'BlzSetSpecialEffectAlpha', 'setAlpha', 128},
        {'BlzSetSpecialEffectTimeScale', 'setTimeScale', 0.5},
        {'BlzSetSpecialEffectOrientation', 'setOrientation', 1, 2, 3}, {'BlzSetSpecialEffectHeight', 'setHeight', 50},
        {'BlzSetSpecialEffectZ', 'setZ', 60}, {'BlzPlaySpecialEffect', 'playAnimation', attack}})
    native('BlzSetSpecialEffectColorByPlayer', function() end)
    e:setPlayerColor(Player.fromIndex(0)); expectCall('BlzSetSpecialEffectColorByPlayer', e.handle, PLAYER_RAW)
    fails(function() e:setPlayerColor(e) end, 'Effect.setPlayerColor: expected Player wrapper')
    eq(callCount('BlzSetSpecialEffectColorByPlayer'), 1)
    e:destroy()
    checkDisposed(e, {'setColor', 'setAlpha', 'setPlayerColor', 'setTimeScale', 'setOrientation', 'setHeight', 'setZ',
        'playAnimation'})
end)

test('flash creates and destroys at once without a wrapper', function()
    local raw = {}
    native('AddSpecialEffect', function() return raw end)
    eq(Effect.flash('boom.mdx', 1, 2), nil)
    eq(callName(1), 'AddSpecialEffect'); eq(callName(2), 'DestroyEffect'); eq(totalCalls(), 2)
    expectCall('AddSpecialEffect', 'boom.mdx', 1, 2); expectCall('DestroyEffect', raw)
    local u = Unit.fromHandle({})
    native('AddSpecialEffectTarget', function() return raw end)
    eq(Effect.flashOn('boom.mdx', u, 'chest'), nil)
    expectCall('AddSpecialEffectTarget', 'boom.mdx', u.handle, 'chest'); eq(callCount('DestroyEffect'), 2)
    native('AddSpecialEffect', function() return nil end)
    fails(function() Effect.flash('m', 0, 0) end, 'Effect.flash')
    native('AddSpecialEffectTarget', function() return nil end)
    fails(function() Effect.flashOn('m', u, 'origin') end, 'Effect.flashOn')
    fails(function() Effect.flashOn('m', {}, 'origin') end, 'Effect.flashOn: expected Widget wrapper')
    eq(callCount('DestroyEffect'), 2)
    native('AddSpecialEffect', function() return {} end)
    native('AddSpecialEffectTarget', function() return {} end)
    u:remove()
end)
