ORIGIN_FRAME_GAME_UI = {}
local byName = {}
local function newFrame(name, parent, context)
    local raw = {name = name, parent = parent, children = {}, context = context}
    if parent then parent.children[#parent.children + 1] = raw end
    byName[name .. '#' .. context] = raw
    return raw
end
-- The 'Panel' template has two parts, found by name with the panel's create context.
local function createFrame(template, parent, _, context)
    local raw = newFrame(template, parent, context)
    if template == 'Panel' then
        newFrame('PanelTitle', raw, context)
        newFrame('PanelClose', raw, context)
    end
    return raw
end
local ORIGIN = newFrame('GameUI', nil, 0)
native('BlzGetOriginFrame', function(_, index) if index == 0 then return ORIGIN end end)
native('BlzCreateFrame', createFrame)
native('BlzCreateSimpleFrame', function(template, parent, context) return newFrame(template, parent, context) end)
native('BlzCreateFrameByType', function(_, name, parent, _, context) return newFrame(name, parent, context) end)
native('BlzGetFrameByName', function(name, context) return byName[name .. '#' .. context] end)
native('BlzFrameGetName', function(raw) return raw.name end)
native('BlzFrameGetParent', function(raw) return raw.parent end)
native('BlzFrameGetChildrenCount', function(raw) return #raw.children end)
native('BlzFrameGetChild', function(raw, index) return raw.children[index + 1] end)
native('BlzLoadTOCFile', function(path) return path == 'ok.toc' end)
for _, name in ipairs({'BlzFrameSetParent', 'BlzDestroyFrame', 'BlzHideOriginFrames', 'BlzEnableUIAutoPosition',
    'DestroyTrigger'}) do
    native(name, function() end)
end
local Frame = require('wrappers.frame')
eq(totalCalls(), 0)

test('factories pass the parent, options and a fresh create context', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    expectCall('BlzGetOriginFrame', ORIGIN_FRAME_GAME_UI, 0)
    eq(ui.handle, ORIGIN); eq(Frame.origin(ORIGIN_FRAME_GAME_UI, 0), ui)
    local a = Frame.create('Panel', ui)
    local context = a.handle.context
    expectCall('BlzCreateFrame', 'Panel', ORIGIN, 0, context)
    local b = Frame.create('Panel', a, {priority = 2})
    expectCall('BlzCreateFrame', 'Panel', a.handle, 2, context + 1)
    local c = Frame.createSimple('Bar', ui)
    expectCall('BlzCreateSimpleFrame', 'Bar', ORIGIN, context + 2)
    local d = Frame.createByType('BUTTON', b, {name = 'Ok', inherits = 'ScriptDialogButton'})
    expectCall('BlzCreateFrameByType', 'BUTTON', 'Ok', b.handle, 'ScriptDialogButton', context + 3)
    local e = Frame.createByType('BACKDROP', ui)
    expectCall('BlzCreateFrameByType', 'BACKDROP', '', ORIGIN, '', context + 4)
    eq(Frame.fromHandle(d.handle), d); eq(Frame.fromHandle(nil), nil)
    eq(d:getHandle(), d.handle); eq(d:isDisposed(), false)
    a:destroy(); c:destroy(); e:destroy()
    eq(d:isDisposed(), true)
end)

test('factories check the parent and options first and raise on nil', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    resetCalls()
    fails(function() Frame.create('Panel', nil) end, 'Frame.create: expected Frame wrapper')
    fails(function() Frame.createSimple('Bar', {}) end, 'Frame.createSimple: expected Frame wrapper')
    fails(function() Frame.createByType('BUTTON', ui, {inherit = 'x'}) end, "Frame.createByType: unknown option 'inherit'")
    failsAt(function() Frame.create('Panel', ui, {priority = 1.5}) end, "Frame.create: 'priority' expected an integer")
    eq(totalCalls(), 0)
    native('BlzCreateFrame', function() return nil end)
    fails(function() Frame.create('Missing', ui) end, 'Frame.create: native returned nil')
    native('BlzCreateFrame', createFrame)
end)

test('origin, byName and fromHandle give borrowed frames that cannot be destroyed', function()
    fails(function() Frame.origin(ORIGIN_FRAME_GAME_UI, 3) end, 'Frame.origin: no frame')
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    eq(Frame.byName('GameUI'), ui); expectCall('BlzGetFrameByName', 'GameUI', 0)
    fails(function() Frame.byName('Nothing', 2) end, 'Frame.byName: no frame named Nothing')
    resetCalls()
    fails(function() ui:destroy() end,
        'Frame.destroy: only frames made by Frame.create, createSimple or createByType can be destroyed')
    eq(totalCalls(), 0); eq(ui:isDisposed(), false)
    local panel = Frame.create('Panel', ui)
    eq(Frame.byName('Panel', panel.handle.context), panel)
    panel:destroy()
    eq(panel:isDisposed(), true)
end)

test('structure: names, parents, children and template parts', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    local panel = Frame.create('Panel', ui)
    eq(panel:getName(), 'Panel'); eq(panel:getParent(), ui); eq(ui:getParent(), nil)
    eq(panel:getChildrenCount(), 2)
    local title = panel:getChild(0)
    eq(title:getName(), 'PanelTitle'); eq(panel:findChild('PanelTitle'), title)
    expectCall('BlzGetFrameByName', 'PanelTitle', panel.handle.context)
    eq(title:getParent(), panel)
    local close = title:findChild('PanelClose')
    eq(close:getName(), 'PanelClose'); eq(panel:getChild(1), close)
    fails(function() panel:getChild(5) end, 'Frame.getChild: no child 5')
    fails(function() panel:findChild('Nope') end, 'Frame.findChild: no frame named Nope in this frame')
    fails(function() ui:findChild('PanelTitle') end, 'Frame.findChild: findChild needs a frame made by Frame.create*')
    resetCalls()
    fails(function() title:destroy() end, 'only frames made by Frame.create')
    eq(totalCalls(), 0)
    local root = newFrame('Root', nil, 0)
    newFrame('RootChild', root, 0)
    local rootFrame = Frame.fromHandle(root)
    local rootChild = rootFrame:getChild(0)
    eq(rootChild:getParent(), rootFrame)
    fails(function() rootChild:destroy() end, 'only frames made by Frame.create')
    panel:destroy()
    eq(title:isDisposed(), true); eq(close:isDisposed(), true)
end)

test('destroy disposes owned descendants and template parts, then destroys once', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    local panel = Frame.create('Panel', ui)
    local title = panel:findChild('PanelTitle')
    local button = Frame.createByType('BUTTON', title)
    local inner = Frame.create('Panel', button)
    local innerTitle = inner:findChild('PanelTitle')
    local other = Frame.create('Panel', ui)
    resetCalls()
    local raw = panel.handle
    panel:destroy(); panel:destroy()
    eq(callCount('BlzDestroyFrame'), 1); expectCall('BlzDestroyFrame', raw)
    for _, frame in ipairs({panel, title, button, inner, innerTitle}) do eq(frame:isDisposed(), true) end
    eq(panel.handle, nil); eq(other:isDisposed(), false)
    checkDisposed(button, {'getHandle', 'getName', 'getParent', 'getChildrenCount', 'getChild', 'findChild',
        'setParent'})
    button:destroy()
    eq(callCount('BlzDestroyFrame'), 1)
    local child = Frame.create('Panel', other)
    child:destroy()
    other:destroy()
    eq(callCount('BlzDestroyFrame'), 3)
end)

test('setParent moves owned frames and refuses parts, borrowed-under-owned and cycles', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    local a, b = Frame.create('Panel', ui), Frame.create('Panel', ui)
    local c = Frame.create('Panel', a)
    c:setParent(b); expectCall('BlzFrameSetParent', c.handle, b.handle)
    a:destroy(); eq(c:isDisposed(), false)
    b:destroy(); eq(c:isDisposed(), true)
    local d, e = Frame.create('Panel', ui), Frame.create('Panel', ui)
    local f = Frame.create('Panel', d)
    f:setParent(ui)
    d:destroy(); eq(f:isDisposed(), false)
    local title = e:findChild('PanelTitle')
    local g = Frame.create('Panel', e)
    resetCalls()
    fails(function() title:setParent(ui) end, 'Frame.setParent: a template part cannot be re-parented')
    fails(function() ui:setParent(e) end, 'Frame.setParent: a borrowed frame can only be re-parented to a borrowed frame')
    fails(function() e:setParent(e) end, 'Frame.setParent: a frame cannot be re-parented into its own subtree')
    fails(function() e:setParent(g) end, 'into its own subtree')
    fails(function() e:setParent(title) end, 'into its own subtree')
    fails(function() e:setParent(nil) end, 'Frame.setParent: expected Frame wrapper')
    eq(totalCalls(), 0)
    local loose = Frame.fromHandle(newFrame('Loose', nil, 0))
    loose:setParent(ui); expectCall('BlzFrameSetParent', loose.handle, ui.handle)
    e:destroy(); f:destroy()
    eq(g:isDisposed(), true)
end)

test('statics load TOC files and toggle the game UI', function()
    Frame.loadTOC('ok.toc'); expectCall('BlzLoadTOCFile', 'ok.toc')
    fails(function() Frame.loadTOC('missing.toc') end, 'Frame.loadTOC: could not load missing.toc')
    Frame.hideOrigin(true); expectCall('BlzHideOriginFrames', true)
    Frame.enableAutoPosition(false); expectCall('BlzEnableUIAutoPosition', false)
end)
