ORIGIN_FRAME_GAME_UI = {}
local byName = {}
local function newFrame(name, parent, context)
    local raw = {name = name, parent = parent, children = {}, context = context}
    if parent then parent.children[#parent.children + 1] = raw end
    byName[name .. '#' .. context] = raw
    return raw
end
-- The 'Panel' template has two parts, found by name with the panel's create context.
local function createFrame(template, parent, _, context)
    local raw = newFrame(template, parent, context)
    if template == 'Panel' then
        newFrame('PanelTitle', raw, context)
        newFrame('PanelClose', raw, context)
    end
    return raw
end
local ORIGIN = newFrame('GameUI', nil, 0)
native('BlzGetOriginFrame', function(_, index) if index == 0 then return ORIGIN end end)
native('BlzCreateFrame', createFrame)
native('BlzCreateSimpleFrame', function(template, parent, context) return newFrame(template, parent, context) end)
native('BlzCreateFrameByType', function(_, name, parent, _, context) return newFrame(name, parent, context) end)
native('BlzGetFrameByName', function(name, context) return byName[name .. '#' .. context] end)
native('BlzFrameGetName', function(raw) return raw.name end)
native('BlzFrameGetParent', function(raw) return raw.parent end)
native('BlzFrameGetChildrenCount', function(raw) return #raw.children end)
native('BlzFrameGetChild', function(raw, index) return raw.children[index + 1] end)
native('BlzLoadTOCFile', function(path) return path == 'ok.toc' end)
for _, name in ipairs({'BlzFrameSetParent', 'BlzDestroyFrame', 'BlzHideOriginFrames', 'BlzEnableUIAutoPosition',
    'DestroyTrigger'}) do
    native(name, function() end)
end
local Frame = require('wrappers.frame')
eq(totalCalls(), 0)

test('factories pass the parent, options and a fresh create context', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    expectCall('BlzGetOriginFrame', ORIGIN_FRAME_GAME_UI, 0)
    eq(ui.handle, ORIGIN); eq(Frame.origin(ORIGIN_FRAME_GAME_UI, 0), ui)
    local a = Frame.create('Panel', ui)
    local context = a.handle.context
    expectCall('BlzCreateFrame', 'Panel', ORIGIN, 0, context)
    local b = Frame.create('Panel', a, {priority = 2})
    expectCall('BlzCreateFrame', 'Panel', a.handle, 2, context + 1)
    local c = Frame.createSimple('Bar', ui)
    expectCall('BlzCreateSimpleFrame', 'Bar', ORIGIN, context + 2)
    local d = Frame.createByType('BUTTON', b, {name = 'Ok', inherits = 'ScriptDialogButton'})
    expectCall('BlzCreateFrameByType', 'BUTTON', 'Ok', b.handle, 'ScriptDialogButton', context + 3)
    local e = Frame.createByType('BACKDROP', ui)
    expectCall('BlzCreateFrameByType', 'BACKDROP', '', ORIGIN, '', context + 4)
    eq(Frame.fromHandle(d.handle), d); eq(Frame.fromHandle(nil), nil)
    eq(d:getHandle(), d.handle); eq(d:isDisposed(), false)
    a:destroy(); c:destroy(); e:destroy()
    eq(d:isDisposed(), true)
end)

test('factories check the parent and options first and raise on nil', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    resetCalls()
    failsAt(function() Frame.create('Panel', nil) end, 'Frame.create: expected Frame wrapper')
    failsAt(function() Frame.createSimple('Bar', {}) end, 'Frame.createSimple: expected Frame wrapper')
    failsAt(function() Frame.createByType('BUTTON', ui, {inherit = 'x'}) end,
        "Frame.createByType: unknown option 'inherit'")
    failsAt(function() Frame.create('Panel', ui, {priority = 1.5}) end, "Frame.create: 'priority' expected an integer")
    eq(totalCalls(), 0)
    native('BlzCreateFrame', function() return nil end)
    failsAt(function() Frame.create('Missing', ui) end, 'Frame.create: native returned nil')
    native('BlzCreateFrame', createFrame)
end)

test('origin, byName and fromHandle give borrowed frames that cannot be destroyed', function()
    failsAt(function() Frame.origin(ORIGIN_FRAME_GAME_UI, 3) end, 'Frame.origin: no frame')
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    eq(Frame.byName('GameUI'), ui); expectCall('BlzGetFrameByName', 'GameUI', 0)
    failsAt(function() Frame.byName('Nothing', 2) end, 'Frame.byName: no frame named Nothing')
    resetCalls()
    failsAt(function() ui:destroy() end,
        'Frame.destroy: only frames made by Frame.create, createSimple or createByType can be destroyed')
    eq(totalCalls(), 0); eq(ui:isDisposed(), false)
    local panel = Frame.create('Panel', ui)
    eq(Frame.byName('Panel', panel.handle.context), panel)
    panel:destroy()
    eq(panel:isDisposed(), true)
end)

test('structure: names, parents, children and template parts', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    local panel = Frame.create('Panel', ui)
    eq(panel:getName(), 'Panel'); eq(panel:getParent(), ui); eq(ui:getParent(), nil)
    eq(panel:getChildrenCount(), 2)
    local title = panel:getChild(0)
    eq(title:getName(), 'PanelTitle'); eq(panel:findChild('PanelTitle'), title)
    expectCall('BlzGetFrameByName', 'PanelTitle', panel.handle.context)
    eq(title:getParent(), panel)
    local close = title:findChild('PanelClose')
    eq(close:getName(), 'PanelClose'); eq(panel:getChild(1), close)
    failsAt(function() panel:getChild(5) end, 'Frame.getChild: no child 5')
    failsAt(function() panel:findChild('Nope') end, 'Frame.findChild: no frame named Nope in this frame')
    failsAt(function() ui:findChild('PanelTitle') end, 'Frame.findChild: findChild needs a frame made by Frame.create*')
    resetCalls()
    failsAt(function() title:destroy() end, 'only frames made by Frame.create')
    eq(totalCalls(), 0)
    local root = newFrame('Root', nil, 0)
    newFrame('RootChild', root, 0)
    local rootFrame = Frame.fromHandle(root)
    local rootChild = rootFrame:getChild(0)
    eq(rootChild:getParent(), rootFrame)
    failsAt(function() rootChild:destroy() end, 'only frames made by Frame.create')
    panel:destroy()
    eq(title:isDisposed(), true); eq(close:isDisposed(), true)
end)

test('destroy disposes owned descendants and template parts, then destroys once', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    local panel = Frame.create('Panel', ui)
    local title = panel:findChild('PanelTitle')
    local button = Frame.createByType('BUTTON', title)
    local inner = Frame.create('Panel', button)
    local innerTitle = inner:findChild('PanelTitle')
    local other = Frame.create('Panel', ui)
    resetCalls()
    local raw = panel.handle
    panel:destroy(); panel:destroy()
    eq(callCount('BlzDestroyFrame'), 1); expectCall('BlzDestroyFrame', raw)
    for _, frame in ipairs({panel, title, button, inner, innerTitle}) do eq(frame:isDisposed(), true) end
    eq(panel.handle, nil); eq(other:isDisposed(), false)
    checkDisposed(button, {'getHandle', 'getName', 'getParent', 'getChildrenCount', 'getChild', 'findChild',
        'setParent'})
    button:destroy()
    eq(callCount('BlzDestroyFrame'), 1)
    local child = Frame.create('Panel', other)
    child:destroy()
    other:destroy()
    eq(callCount('BlzDestroyFrame'), 3)
end)

test('setParent moves owned frames and refuses parts, borrowed-under-owned and cycles', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    local a, b = Frame.create('Panel', ui), Frame.create('Panel', ui)
    local c = Frame.create('Panel', a)
    c:setParent(b); expectCall('BlzFrameSetParent', c.handle, b.handle)
    a:destroy(); eq(c:isDisposed(), false)
    b:destroy(); eq(c:isDisposed(), true)
    local d, e = Frame.create('Panel', ui), Frame.create('Panel', ui)
    local f = Frame.create('Panel', d)
    f:setParent(ui)
    d:destroy(); eq(f:isDisposed(), false)
    local title = e:findChild('PanelTitle')
    local g = Frame.create('Panel', e)
    resetCalls()
    failsAt(function() title:setParent(ui) end, 'Frame.setParent: a template part cannot be re-parented')
    failsAt(function() ui:setParent(e) end,
        'Frame.setParent: a borrowed frame can only be re-parented to a borrowed frame')
    failsAt(function() e:setParent(e) end, 'Frame.setParent: a frame cannot be re-parented into its own subtree')
    failsAt(function() e:setParent(g) end, 'into its own subtree')
    failsAt(function() e:setParent(title) end, 'into its own subtree')
    failsAt(function() e:setParent(nil) end, 'Frame.setParent: expected Frame wrapper')
    eq(totalCalls(), 0)
    local loose = Frame.fromHandle(newFrame('Loose', nil, 0))
    loose:setParent(ui); expectCall('BlzFrameSetParent', loose.handle, ui.handle)
    e:destroy(); f:destroy()
    eq(g:isDisposed(), true)
end)

test('statics load TOC files and toggle the game UI', function()
    Frame.loadTOC('ok.toc'); expectCall('BlzLoadTOCFile', 'ok.toc')
    failsAt(function() Frame.loadTOC('missing.toc') end, 'Frame.loadTOC: could not load missing.toc')
    Frame.setOriginHidden(true); expectCall('BlzHideOriginFrames', true)
    Frame.setOriginHidden(false); expectCall('BlzHideOriginFrames', false)
    Frame.setAutoPosition(false); expectCall('BlzEnableUIAutoPosition', false)
    Frame.setAutoPosition(true); expectCall('BlzEnableUIAutoPosition', true)
    eq(Frame.hideOrigin, nil); eq(Frame.enableAutoPosition, nil)
end)

test('a template part first reached as borrowed becomes a part when it is found through its owner', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    -- Frame.byName first, then findChild: the same wrapper.
    local panel = Frame.create('Panel', ui)
    local title = Frame.byName('PanelTitle', panel.handle.context)
    eq(panel:findChild('PanelTitle'), title)
    -- It is a part from then on: it can be neither destroyed nor moved.
    resetCalls()
    failsAt(function() title:destroy() end, 'Frame.destroy: only frames made by Frame.create')
    failsAt(function() title:setParent(ui) end, 'Frame.setParent: a template part cannot be re-parented')
    eq(totalCalls(), 0)
    -- Its owner's destroy disposes it, and it is recorded once however often it is found.
    eq(panel:getChild(0), title); eq(panel:findChild('PanelTitle'), title)
    panel:destroy()
    eq(title:isDisposed(), true)
    failsAt(function() title:getName() end, 'Frame.getName: Frame is disposed')
    -- The control: findChild first, then Frame.byName.
    local second = Frame.create('Panel', ui)
    local found = second:findChild('PanelTitle')
    eq(Frame.byName('PanelTitle', second.handle.context), found)
    second:destroy()
    eq(found:isDisposed(), true)
    -- Frame.fromHandle first, then getChild.
    local third = Frame.create('Panel', ui)
    local close = Frame.fromHandle(third.handle.children[2])
    eq(third:getChild(1), close)
    third:destroy()
    eq(close:isDisposed(), true)
    -- A part's parent that was reached as borrowed first stays borrowed through getParent; getChild makes it a part.
    local fourth = Frame.create('Panel', ui)
    newFrame('PanelInner', fourth.handle.children[1], fourth.handle.context)
    local middle = Frame.fromHandle(fourth.handle.children[1])
    local inner = fourth:findChild('PanelInner')
    eq(inner:getParent(), middle)
    eq(fourth:getChild(0), middle)
    fourth:destroy()
    eq(middle:isDisposed(), true); eq(inner:isDisposed(), true)
    -- A frame of the game's that no owned frame leads to stays borrowed.
    local loose = Frame.fromHandle(newFrame('LooseTwo', nil, 0))
    loose:setParent(ui)
    failsAt(function() loose:destroy() end, 'Frame.destroy: only frames made by Frame.create')
end)

test('lookups check their integers and show no table address', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    local panel = Frame.create('Panel', ui)
    resetCalls()
    for _, bad in ipairs({1.5, 2 ^ 31, 0 / 0, '1', {}}) do
        failsAt(function() Frame.origin(ORIGIN_FRAME_GAME_UI, bad) end, 'Frame.origin: expected an integer index')
        failsAt(function() Frame.byName('GameUI', bad) end, 'Frame.byName: expected an integer context')
        failsAt(function() panel:getChild(bad) end, 'Frame.getChild: expected an integer index')
    end
    failsAt(function() panel:getChild(nil) end, 'Frame.getChild: expected an integer index')
    eq(totalCalls(), 0)
    eq(panel:getChild(1.0), panel:getChild(1))
    native('BlzGetFrameByName', function() return nil end)
    failsAt(function() Frame.byName({}) end, 'Frame.byName: no frame named <table>')
    failsAt(function() panel:findChild(print) end, 'Frame.findChild: no frame named <function> in this frame')
    failsAt(function() Frame.loadTOC({}) end, 'Frame.loadTOC: could not load <table>')
    native('BlzGetFrameByName', function(name, context) return byName[name .. '#' .. context] end)
    panel:destroy()
end)

test('a frame reached through getParent, or an origin frame, is never made a part', function()
    local ui = Frame.origin(ORIGIN_FRAME_GAME_UI)
    native('BlzFrameSetParent', function(raw, parent) raw.parent = parent end)
    -- Chain B1: a borrowed part moved under the game UI, then found through its owner, then asked for its parent.
    local panel = Frame.create('Panel', ui)
    local title = Frame.byName('PanelTitle', panel.handle.context)
    title:setParent(ui)
    eq(panel:findChild('PanelTitle'), title)
    eq(title:getParent(), ui)
    panel:destroy()
    eq(title:isDisposed(), true)
    eq(ui:isDisposed(), false)
    local holder = Frame.fromHandle(newFrame('HolderB1', nil, 0))
    ui:setParent(holder)
    local again = Frame.create('Panel', ui)
    again:destroy()
    -- A converted part whose parent is a known borrowed frame gets that same wrapper, and it stays borrowed.
    local second = Frame.create('Panel', ui)
    local middle = Frame.fromHandle(newFrame('MiddleBorrowed', nil, 0))
    local part = Frame.byName('PanelTitle', second.handle.context)
    part:setParent(middle)
    eq(second:findChild('PanelTitle'), part)
    eq(part:getParent(), middle)
    second:destroy()
    eq(part:isDisposed(), true); eq(middle:isDisposed(), false)
    middle:setParent(ui)
    failsAt(function() middle:destroy() end, 'Frame.destroy: only frames made by Frame.create')
    -- An origin frame that an owned frame's getChild or findChild returns stays borrowed.
    local third = Frame.create('Panel', ui)
    native('BlzFrameGetChild', function(raw, index)
        if raw == third.handle and index == 7 then return ORIGIN end
        return raw.children[index + 1]
    end)
    native('BlzGetFrameByName', function(name, context)
        if name == 'OriginAlias' then return ORIGIN end
        return byName[name .. '#' .. context]
    end)
    eq(third:getChild(7), ui); eq(third:findChild('OriginAlias'), ui)
    third:destroy()
    eq(ui:isDisposed(), false)
    local fourth = Frame.create('Panel', ui)
    fourth:destroy()
    native('BlzFrameGetChild', function(raw, index) return raw.children[index + 1] end)
    native('BlzGetFrameByName', function(name, context) return byName[name .. '#' .. context] end)
    native('BlzFrameSetParent', function() end)
end)
