native('CreateGroup', function() return {} end)
native('DestroyGroup', function() end)
local Group = require('wrappers.group')
local Unit = require('wrappers.unit')
eq(totalCalls(), 0)

test('group membership forwards native arguments without owning units', function()
    local g, u = Group.create(), Unit.fromHandle({})
    eq(Group.fromHandle(nil), nil); eq(Group.fromHandle(g.handle), g)
    for _, name in ipairs({'GroupAddUnit', 'GroupRemoveUnit', 'GroupClear'}) do native(name, function() end) end
    native('IsUnitInGroup', function() return true end)
    g:add(u); expectCall('GroupAddUnit', g.handle, u.handle)
    eq(g:contains(u), true); expectCall('IsUnitInGroup', u.handle, g.handle)
    g:remove(u); expectCall('GroupRemoveUnit', g.handle, u.handle)
    g:clear(); expectCall('GroupClear', g.handle)
    local raw = g:getHandle(); g:destroy(); g:destroy()
    expectCall('DestroyGroup', raw); eq(callCount('DestroyGroup'), 1)
    eq(callCount('RemoveUnit'), 0); eq(u:isDisposed(), false); eq(g.handle, nil)
    for _, method in ipairs({'getHandle', 'add', 'remove', 'contains', 'clear', 'enumInRange', 'getSize', 'getUnits'}) do
        fails(function() g[method](g) end, 'disposed')
    end
    u:remove()
    native('CreateGroup', function() return nil end); fails(Group.create, 'Group.create')
    native('CreateGroup', function() return {} end)
end)

test('range validation preserves group on failure and enumeration clears first', function()
    local g = Group.create()
    native('GroupEnumUnitsInRange', function() end)
    for _, radius in ipairs({-1, math.huge, 0/0, '1'}) do
        fails(function() g:enumInRange(0, 0, radius) end, 'Group.enumInRange')
    end
    eq(callCount('GroupClear'), 0)
    resetCalls(); g:enumInRange(10, 20, 0)
    eq(callName(1), 'GroupClear'); eq(callName(2), 'GroupEnumUnitsInRange')
    expectCall('GroupEnumUnitsInRange', g.handle, 10, 20, 0, nil)
    local u = Unit.fromHandle({}); u:remove()
    fails(function() g:add(u) end, 'disposed')
    fails(function() g:contains(g) end, 'Unit')
    fails(function() g:remove({}) end, 'Unit')
    eq(callCount('GroupAddUnit'), 0); eq(callCount('IsUnitInGroup'), 0); eq(callCount('GroupRemoveUnit'), 0)
    g:destroy()
end)

test('snapshots are dense independent arrays preserving wrapper identity', function()
    local a, b, g = {}, {}, Group.create()
    native('BlzGroupGetSize', function() return 3 end)
    native('BlzGroupUnitAt', function(_, index) return ({[0] = a, [2] = b})[index] end)
    eq(g:getSize(), 3); expectCall('BlzGroupGetSize', g.handle)
    local first, second = g:getUnits(), g:getUnits()
    assert(first ~= second); eq(#first, 2)
    eq(first[1], Unit.fromHandle(a)); eq(first[2], Unit.fromHandle(b))
    expectCall('BlzGroupUnitAt', g.handle, 2)
    g:clear(); eq(#first, 2)
    first[1]:remove(); eq(first[1]:isDisposed(), true); eq(second[1]:isDisposed(), true)
    first[2]:remove(); g:destroy()
end)
