for _, name in ipairs({'SetImageRenderAlways', 'ShowImage', 'SetImagePosition', 'SetImageColor',
    'SetImageConstantHeight', 'SetImageAboveWater', 'SetImageType', 'DestroyImage'}) do
    native(name, function() end)
end
native('CreateImage', function() return {} end)
native('GetHandleId', function() return 8 end)
native('GetLocalPlayer', function() return PLAYER_RAW end)
local Image = require('wrappers.image')
local Player = require('wrappers.player')
eq(totalCalls(), 0)

test('images are centered on creation, drawn and shown', function()
    eq(Image.fromHandle(nil), nil)
    local image = Image.create('aoe.blp', 256, 128, 100, 50, 1)
    expectCall('CreateImage', 'aoe.blp', 256, 128, 0, -28, -14, 0, 0, 0, 0, 1)
    expectCall('SetImageRenderAlways', image.handle, true); expectCall('ShowImage', image.handle, true)
    eq(Image.fromHandle(image.handle), image); eq(image:getHandle(), image.handle); eq(image:isDisposed(), false)
    image:setPosition(0, 0); expectCall('SetImagePosition', image.handle, -128, -64, 0)
    image:setPosition(10, 20, 5); expectCall('SetImagePosition', image.handle, -118, -44, 5)
    image:destroy()
end)

test('create and setPosition accept a fraction, zero and a negative coordinate', function()
    local image = Image.create('aoe.blp', 64, 32, 0.5, -100, 1)
    expectCall('CreateImage', 'aoe.blp', 64, 32, 0, -31.5, -116, 0, 0, 0, 0, 1)
    image:setPosition(-0.25, 0); expectCall('SetImagePosition', image.handle, -32.25, -16, 0)
    image:setPosition(0, -7.5); expectCall('SetImagePosition', image.handle, -32, -23.5, 0)
    image:destroy()
    local atZero = Image.create('aoe.blp', 64, 32, 0, 0, 1)
    expectCall('CreateImage', 'aoe.blp', 64, 32, 0, -32, -16, 0, 0, 0, 0, 1)
    atZero:destroy()
end)

test('a wrapped image of unknown size cannot be centered', function()
    local foreign = Image.fromHandle({})
    failsAt(function() foreign:setPosition(0, 0) end,
        'Image.setPosition: size unknown for a wrapped image; use SetImagePosition')
    eq(callCount('SetImagePosition'), 0)
    foreign:destroy()
end)

test('image settings and local visibility forward exact arguments', function()
    local image = Image.create('aoe.blp', 64, 64, 0, 0, 2)
    checkSetters(image, {{'ShowImage', 'setVisible', false}, {'SetImageColor', 'setColor', 1, 2, 3, 4},
        {'SetImageConstantHeight', 'setConstantHeight', true, 10}, {'SetImageAboveWater', 'setAboveWater', true, false},
        {'SetImageType', 'setType', 3}})
    image:setVisibleFor(Player.fromIndex(0)); expectCall('ShowImage', image.handle, true)
    image:setVisibleFor(Player.fromHandle({})); expectCall('ShowImage', image.handle, false)
    failsAt(function() image:setVisibleFor(image) end, 'Image.setVisibleFor: expected Player wrapper')
    image:destroy()
end)

test('image destruction is idempotent and guards every method', function()
    local image = Image.create('aoe.blp', 64, 64, 0, 0, 1)
    local raw = image.handle
    image:destroy(); image:destroy()
    expectCall('DestroyImage', raw); eq(callCount('DestroyImage'), 1); eq(image.handle, nil)
    eq(image:isDisposed(), true)
    checkDisposed(image, {'getHandle', 'setPosition', 'setVisible', 'setVisibleFor', 'setColor', 'setConstantHeight',
        'setAboveWater', 'setType'})
    native('CreateImage', function() return nil end)
    failsAt(function() Image.create('aoe.blp', 64, 64, 0, 0, 1) end, 'Image.create')
    eq(callCount('SetImageRenderAlways'), 1)
    native('CreateImage', function() return {} end)
end)

test('a wrong image path raises and destroys the invalid image', function()
    local invalid = {}
    native('CreateImage', function() return invalid end)
    native('GetHandleId', function(raw) return raw == invalid and -1 or 8 end)
    failsAt(function() Image.create('missing.blp', 64, 64, 0, 0, 1) end,
        'Image.create: invalid image path: missing.blp')
    expectCall('DestroyImage', invalid); eq(callCount('DestroyImage'), 1)
    failsAt(function() Image.create({}, 64, 64, 0, 0, 1) end, 'Image.create: invalid image path: <table>')
    eq(callCount('DestroyImage'), 2)
    eq(callCount('SetImageRenderAlways'), 0); eq(callCount('ShowImage'), 0)
    native('CreateImage', function() return {} end)
    native('GetHandleId', function() return 8 end)
end)

test('create and setPosition refuse a number that is missing or not finite, at the caller', function()
    resetCalls()
    failsAt(function() Image.create('aoe.blp', nil, 64, 0, 0, 1) end, 'Image.create: expected a finite width')
    failsAt(function() Image.create('aoe.blp', 64, 'tall', 0, 0, 1) end, 'Image.create: expected a finite height')
    failsAt(function() Image.create('aoe.blp', 64, 64, math.huge, 0, 1) end, 'Image.create: expected a finite x')
    failsAt(function() Image.create('aoe.blp', 64, 64, 0, nil, 1) end, 'Image.create: expected a finite y')
    eq(totalCalls(), 0)
    local image = Image.create('aoe.blp', 64, 64, 0, 0, 1)
    resetCalls()
    failsAt(function() image:setPosition(nil, 0) end, 'Image.setPosition: expected a finite x')
    failsAt(function() image:setPosition(0) end, 'Image.setPosition: expected a finite y')
    eq(totalCalls(), 0)
    image:destroy()
    eq(Image.show, nil)
end)
