native('AddLightningEx', function() return {} end)
native('DestroyLightning', function() return true end)
native('MoveLightningEx', function() return true end)
native('SetLightningColor', function() return false end)
local Lightning = require('wrappers.lightning')
eq(totalCalls(), 0)

test('lightning creation, movement and color forward exact arguments', function()
    eq(Lightning.fromHandle(nil), nil)
    local bolt = Lightning.create('CLPB', 1, 2, 3, 4, 5, 6)
    expectCall('AddLightningEx', 'CLPB', false, 1, 2, 3, 4, 5, 6)
    eq(Lightning.fromHandle(bolt.handle), bolt); eq(bolt:getHandle(), bolt.handle); eq(bolt:isDisposed(), false)
    local checked = Lightning.create('DRAL', 1, 2, 3, 4, 5, 6, true)
    expectCall('AddLightningEx', 'DRAL', true, 1, 2, 3, 4, 5, 6)
    eq(bolt:move(7, 8, 9, 10, 11, 12), true); expectCall('MoveLightningEx', bolt.handle, false, 7, 8, 9, 10, 11, 12)
    bolt:move(0, 0, 0, 1, 1, 1, true); expectCall('MoveLightningEx', bolt.handle, true, 0, 0, 0, 1, 1, 1)
    eq(bolt:setColor(255, 0, 51, 255), false); expectCall('SetLightningColor', bolt.handle, 1, 0, 0.2, 1)
    bolt:destroy(); checked:destroy()
end)

test('lightning destruction is idempotent and guards every method', function()
    local bolt = Lightning.create('CLPB', 0, 0, 0, 1, 1, 1)
    local raw = bolt.handle
    bolt:destroy(); bolt:destroy()
    expectCall('DestroyLightning', raw); eq(callCount('DestroyLightning'), 1); eq(bolt.handle, nil)
    eq(bolt:isDisposed(), true)
    checkDisposed(bolt, {'getHandle', 'move', 'setColor'})
    native('AddLightningEx', function() return nil end)
    failsAt(function() Lightning.create('CLPB', 0, 0, 0, 1, 1, 1) end, 'Lightning.create')
    native('AddLightningEx', function() return {} end)
end)

test('setColor takes whole channels from 0 to 255 and refuses anything else at the caller', function()
    local bolt = Lightning.create('CLPB', 0, 0, 0, 1, 1, 1)
    resetCalls()
    bolt:setColor(0, 255, 255.0, 0); expectCall('SetLightningColor', bolt.handle, 0, 1, 1, 0)
    resetCalls()
    failsAt(function() bolt:setColor(0.5, 0, 0, 255) end, 'Lightning.setColor: expected an integer red from 0 to 255')
    failsAt(function() bolt:setColor(0, 256, 0, 255) end, 'Lightning.setColor: expected an integer green from 0 to 255')
    failsAt(function() bolt:setColor(0, 0, -1, 255) end, 'Lightning.setColor: expected an integer blue from 0 to 255')
    failsAt(function() bolt:setColor(0, 0, 0) end, 'Lightning.setColor: expected an integer alpha from 0 to 255')
    failsAt(function() bolt:setColor('255', 0, 0, 255) end, 'Lightning.setColor: expected an integer red from 0 to 255')
    eq(totalCalls(), 0)
    bolt:destroy()
end)

test('a code that is not a string fails at the caller, before any native', function()
    resetCalls()
    for _, bad in ipairs({false, 7, {}}) do
        failsAt(function() Lightning.create(bad, 0, 0, 0, 1, 1, 1) end, 'Lightning.create: expected a lightning code')
    end
    failsAt(function() Lightning.create(nil, 0, 0, 0, 1, 1, 1) end, 'Lightning.create: expected a lightning code')
    eq(totalCalls(), 0)
end)
