native('AddLightningEx', function() return {} end)
native('DestroyLightning', function() return true end)
native('MoveLightningEx', function() return true end)
native('SetLightningColor', function() return false end)
local Lightning = require('wrappers.lightning')
eq(totalCalls(), 0)

test('lightning creation, movement and color forward exact arguments', function()
    eq(Lightning.fromHandle(nil), nil)
    local bolt = Lightning.create('CLPB', 1, 2, 3, 4, 5, 6)
    expectCall('AddLightningEx', 'CLPB', false, 1, 2, 3, 4, 5, 6)
    eq(Lightning.fromHandle(bolt.handle), bolt); eq(bolt:getHandle(), bolt.handle); eq(bolt:isDisposed(), false)
    local checked = Lightning.create('DRAL', 1, 2, 3, 4, 5, 6, true)
    expectCall('AddLightningEx', 'DRAL', true, 1, 2, 3, 4, 5, 6)
    eq(bolt:move(7, 8, 9, 10, 11, 12), true); expectCall('MoveLightningEx', bolt.handle, false, 7, 8, 9, 10, 11, 12)
    bolt:move(0, 0, 0, 1, 1, 1, true); expectCall('MoveLightningEx', bolt.handle, true, 0, 0, 0, 1, 1, 1)
    eq(bolt:setColor(1, 0.5, 0, 1), false); expectCall('SetLightningColor', bolt.handle, 1, 0.5, 0, 1)
    bolt:destroy(); checked:destroy()
end)

test('lightning destruction is idempotent and guards every method', function()
    local bolt = Lightning.create('CLPB', 0, 0, 0, 1, 1, 1)
    local raw = bolt.handle
    bolt:destroy(); bolt:destroy()
    expectCall('DestroyLightning', raw); eq(callCount('DestroyLightning'), 1); eq(bolt.handle, nil)
    eq(bolt:isDisposed(), true)
    checkDisposed(bolt, {'getHandle', 'move', 'setColor'})
    native('AddLightningEx', function() return nil end)
    fails(function() Lightning.create('CLPB', 0, 0, 0, 1, 1, 1) end, 'Lightning.create')
    native('AddLightningEx', function() return {} end)
end)
