native('CreateRegion', function() return {} end)
native('RemoveRegion', function() end)
native('Rect', function() return {} end)
native('RemoveRect', function() end)
local Region = require('wrappers.region')
local Rect = require('wrappers.rect')
local Unit = require('wrappers.unit')
eq(totalCalls(), 0)

test('region areas and queries forward wrapped arguments', function()
    local g, r, u = Region.create(), Rect.create(0, 0, 1, 1), Unit.fromHandle({})
    eq(Region.fromHandle(nil), nil); eq(Region.fromHandle(g.handle), g)
    for _, name in ipairs({'RegionAddRect', 'RegionClearRect', 'RegionAddCell', 'RegionClearCell'}) do
        native(name, function() end)
    end
    g:addRect(r); expectCall('RegionAddRect', g.handle, r.handle)
    g:clearRect(r); expectCall('RegionClearRect', g.handle, r.handle)
    g:addCell(5, 6); expectCall('RegionAddCell', g.handle, 5, 6)
    g:clearCell(5, 6); expectCall('RegionClearCell', g.handle, 5, 6)
    native('IsPointInRegion', function() return true end)
    eq(g:containsPoint(1, 2), true); expectCall('IsPointInRegion', g.handle, 1, 2)
    native('IsUnitInRegion', function() return false end)
    eq(g:containsUnit(u), false); expectCall('IsUnitInRegion', g.handle, u.handle)
    fails(function() g:addRect(u) end, 'Region.addRect: expected Rect wrapper')
    fails(function() g:containsUnit(r) end, 'Region.containsUnit: expected Unit wrapper')
    eq(callCount('RegionAddRect'), 1); eq(callCount('IsUnitInRegion'), 1)
    local raw = g.handle
    g:destroy(); g:destroy()
    expectCall('RemoveRegion', raw); eq(callCount('RemoveRegion'), 1); eq(callCount('RemoveRect'), 0)
    checkDisposed(g, {'getHandle', 'addRect', 'clearRect', 'addCell', 'clearCell', 'containsPoint', 'containsUnit'})
    r:destroy(); u:remove()
    native('CreateRegion', function() return nil end); fails(Region.create, 'Region.create')
    native('CreateRegion', function() return {} end)
end)

test('fromEvent wraps the region of the running event, and nil when it has none', function()
    local raw = {}
    native('GetTriggeringRegion', function() return raw end)
    local found = Region.fromEvent()
    eq(found, Region.fromHandle(raw)); eq(found.handle, raw); eq(callCount('GetTriggeringRegion'), 1)
    native('GetTriggeringRegion', function() return nil end)
    eq(Region.fromEvent(), nil)
end)
