for _, name in ipairs({'StartSound', 'StopSound', 'KillSoundWhenDone', 'SetSoundVolume', 'SetSoundPitch',
    'SetSoundChannel', 'SetSoundPosition', 'AttachSoundToUnit', 'SetSoundDistances', 'SetSoundDistanceCutoff'}) do
    native(name, function() end)
end
native('CreateSound', function() return {} end)
native('GetLocalPlayer', function() return PLAYER_RAW end)
local Sound = require('wrappers.sound')
local Player = require('wrappers.player')
local Unit = require('wrappers.unit')
eq(totalCalls(), 0)

test('create uses documented defaults and options', function()
    eq(Sound.fromHandle(nil), nil)
    local s = Sound.create('a.flac')
    expectCall('CreateSound', 'a.flac', false, false, false, 10, 10, 'DefaultEAXON')
    eq(Sound.fromHandle(s.handle), s); eq(s:getHandle(), s.handle); eq(s:isDisposed(), false)
    local looped = Sound.create('b.flac', {looping = true, is3D = true, stopWhenOutOfRange = true, fadeIn = 1,
        fadeOut = 2, eax = 'SpellsEAX'})
    expectCall('CreateSound', 'b.flac', true, true, true, 1, 2, 'SpellsEAX')
    failsAt(function() Sound.create('c.flac', {loop = true}) end, "Sound.create: unknown option 'loop'")
    failsAt(function() Sound.create('c.flac', {fadeIn = 0.5}) end, "Sound.create: 'fadeIn' expected an integer")
    failsAt(function() Sound.create('c.flac', {fadeIn = 2 ^ 40}) end, "Sound.create: 'fadeIn' expected an integer")
    failsAt(function() Sound.create('c.flac', Unit.fromHandle({})) end, 'Sound.create: expected an options table')
    eq(callCount('CreateSound'), 2)
    native('CreateSound', function() return nil end)
    failsAt(function() Sound.create('d.flac') end, 'Sound.create')
    native('CreateSound', function() return {} end)
    s:destroy(); looped:destroy()
end)

test('playback and settings forward exact arguments', function()
    local s = Sound.create('a.flac')
    checkSetters(s, {{'StartSound', 'play'}, {'SetSoundVolume', 'setVolume', 100}, {'SetSoundPitch', 'setPitch', 1.5},
        {'SetSoundChannel', 'setChannel', 5}, {'SetSoundPosition', 'setPosition', 1, 2, 3},
        {'SetSoundDistances', 'setDistances', 600, 4000}, {'SetSoundDistanceCutoff', 'setDistanceCutoff', 3000}})
    native('GetSoundDuration', function() return 1500 end)
    eq(s:getDuration(), 1.5); expectCall('GetSoundDuration', s.handle)
    native('GetSoundDuration', function() return 0 end)
    eq(s:getDuration(), 0)
    s:stop(); expectCall('StopSound', s.handle, false, false)
    s:stop(true); expectCall('StopSound', s.handle, false, true)
    local u = Unit.fromHandle({})
    s:attachToUnit(u); expectCall('AttachSoundToUnit', s.handle, u.handle)
    failsAt(function() s:attachToUnit(s) end, 'Sound.attachToUnit: expected Unit wrapper')
    eq(callCount('AttachSoundToUnit'), 1)
    u:remove(); s:destroy()
end)

test('playFor starts the sound only on that player machine', function()
    local s = Sound.create('a.flac')
    s:playFor(Player.fromIndex(0)); eq(callCount('StartSound'), 1); expectCall('StartSound', s.handle)
    s:playFor(Player.fromHandle({})); eq(callCount('StartSound'), 1)
    failsAt(function() s:playFor(s) end, 'Sound.playFor: expected Player wrapper')
    s:destroy()
end)

test('destroy stops and kills once, never when done, and guards every method', function()
    local s = Sound.create('a.flac')
    local raw = s.handle
    s:destroy(); s:destroy()
    expectCall('StopSound', raw, true, false); eq(callCount('StopSound'), 1); eq(s.handle, nil)
    eq(s:isDisposed(), true); eq(callCount('KillSoundWhenDone'), 0)
    checkDisposed(s, {'getHandle', 'play', 'playFor', 'stop', 'setVolume', 'setPitch', 'setChannel', 'setPosition',
        'attachToUnit', 'setDistances', 'setDistanceCutoff', 'getDuration'})
end)

test('playOnce starts and releases a sound without a wrapper', function()
    local raw = {}
    native('CreateSound', function() return raw end)
    eq(Sound.playOnce('hit.flac'), nil)
    expectCall('CreateSound', 'hit.flac', false, false, false, 10, 10, 'DefaultEAXON')
    expectCall('SetSoundVolume', raw, 127); expectCall('StartSound', raw); expectCall('KillSoundWhenDone', raw)
    eq(callCount('SetSoundPosition'), 0); eq(callCount('GetLocalPlayer'), 0)
    eq(callName(totalCalls()), 'KillSoundWhenDone')
    Sound.playOnce('hit.flac', {volume = 90, x = 1, y = 2})
    expectCall('CreateSound', 'hit.flac', false, true, false, 10, 10, 'DefaultEAXON')
    expectCall('SetSoundVolume', raw, 90); expectCall('SetSoundPosition', raw, 1, 2, 0)
    Sound.playOnce('hit.flac', {x = 1, y = 2, z = 3}); expectCall('SetSoundPosition', raw, 1, 2, 3)
    native('CreateSound', function() return {} end)
end)

test('playOnce for one player mutes the other machines but starts and releases everywhere', function()
    local raw = {}
    native('CreateSound', function() return raw end)
    Sound.playOnce('hit.flac', {player = Player.fromHandle({})})
    expectCall('SetSoundVolume', raw, 0); expectCall('StartSound', raw); expectCall('KillSoundWhenDone', raw)
    Sound.playOnce('hit.flac', {player = Player.fromIndex(0), volume = 50})
    expectCall('SetSoundVolume', raw, 50)
    eq(callCount('StartSound'), 2); eq(callCount('KillSoundWhenDone'), 2)
    native('CreateSound', function() return {} end)
end)

test('playOnce validates before creating a sound and fails on a nil sound', function()
    failsAt(function() Sound.playOnce('a', {x = 1}) end, 'Sound.playOnce: options x and y must be given together')
    failsAt(function() Sound.playOnce('a', {y = 1}) end, 'Sound.playOnce: options x and y must be given together')
    failsAt(function() Sound.playOnce('a', {volume = 'loud'}) end, "Sound.playOnce: 'volume' expected an integer")
    eq(callCount('CreateSound'), 0)
    native('CreateSound', function() return nil end)
    failsAt(function() Sound.playOnce('missing.flac') end, 'Sound.playOnce')
    eq(callCount('StartSound'), 0)
    native('CreateSound', function() return {} end)
end)
