local ids = {}
native('AddWeatherEffect', function() return {} end)
native('EnableWeatherEffect', function() end)
native('RemoveWeatherEffect', function() end)
native('GetHandleId', function(raw)
    assert(raw ~= nil, 'GetHandleId of nil')
    return ids[raw] or 1
end)
native('GetLocalPlayer', function() return PLAYER_RAW end)
local WeatherEffect = require('wrappers.weathereffect')
local Rect = require('wrappers.rect')
local Player = require('wrappers.player')
eq(totalCalls(), 0)

test('a weather effect is created over a rect it does not own, and is not enabled', function()
    eq(WeatherEffect.fromHandle(nil), nil)
    local area = Rect.fromHandle({})
    local rain = WeatherEffect.create(area, 1380018290)
    expectCall('AddWeatherEffect', area.handle, 1380018290)
    eq(WeatherEffect.fromHandle(rain.handle), rain); eq(rain:getHandle(), rain.handle); eq(rain:isDisposed(), false)
    eq(callCount('EnableWeatherEffect'), 0)
    rain:destroy()
    eq(area:isDisposed(), false)
end)

test('enable passes the flag, and enableFor compares with the local player', function()
    local rain = WeatherEffect.create(Rect.fromHandle({}), 1380018290)
    checkSetters(rain, {{'EnableWeatherEffect', 'enable', true}})
    rain:enableFor(Player.fromIndex(0)); expectCall('EnableWeatherEffect', rain.handle, true)
    rain:enableFor(Player.fromHandle({})); expectCall('EnableWeatherEffect', rain.handle, false)
    failsAt(function() rain:enableFor(rain) end, 'WeatherEffect.enableFor: expected Player wrapper')
    eq(callCount('EnableWeatherEffect'), 4)
    rain:destroy()
end)

test('an unknown id is removed and raises at the caller; a nil result and a wrong rect raise too', function()
    local area, invalid = Rect.fromHandle({}), {}
    ids[invalid] = -1
    native('AddWeatherEffect', function() return invalid end)
    failsAt(function() WeatherEffect.create(area, 2054847098) end,
        'WeatherEffect.create: unknown weather effect id: 2054847098')
    expectCall('RemoveWeatherEffect', invalid); eq(callCount('RemoveWeatherEffect'), 1)
    native('AddWeatherEffect', function() return nil end)
    failsAt(function() WeatherEffect.create(area, 1) end, 'WeatherEffect.create: native returned nil')
    native('AddWeatherEffect', function() return {} end)
    resetCalls()
    failsAt(function() WeatherEffect.create({}, 1) end, 'WeatherEffect.create: expected Rect wrapper')
    eq(totalCalls(), 0)
end)

test('destroy is idempotent and guards every method', function()
    local rain = WeatherEffect.create(Rect.fromHandle({}), 1380018290)
    local raw = rain.handle
    rain:destroy(); rain:destroy()
    expectCall('RemoveWeatherEffect', raw); eq(callCount('RemoveWeatherEffect'), 1); eq(rain.handle, nil)
    eq(rain:isDisposed(), true)
    checkDisposed(rain, {'getHandle', 'enable', 'enableFor'})
end)

test('a handle the game uses again gets a wrapper of its own', function()
    local shared = {}
    native('AddWeatherEffect', function() return shared end)
    local area = Rect.fromHandle({})
    local first = WeatherEffect.create(area, 1380018290)
    first:destroy()
    local second = WeatherEffect.create(area, 1380018290)
    eq(second ~= first, true); eq(second.handle, shared); eq(first:isDisposed(), true); eq(second:isDisposed(), false)
    second:enable(true); expectCall('EnableWeatherEffect', shared, true)
    fails(function() first:enable(true) end, 'WeatherEffect.enable: WeatherEffect is disposed')
    second:destroy()
    native('AddWeatherEffect', function() return {} end)
end)
