---Annotation-only base of Unit, Item and Destructable: this file holds no code and no module requires it. There is no
---Widget module class and no Widget.fromHandle: Warcraft has no reliable handle-type check to pick the wrapper class
---for a raw widget. Each of the three classes writes the four shared methods out itself.
---@class MoonwellWrappers.Widget
---@field getHandle fun(self: MoonwellWrappers.Widget): widget
---@field isDisposed fun(self: MoonwellWrappers.Widget): boolean
---@field getLife fun(self: MoonwellWrappers.Widget): number
---@field setLife fun(self: MoonwellWrappers.Widget, value: number)
---@field getX fun(self: MoonwellWrappers.Widget): number
---@field getY fun(self: MoonwellWrappers.Widget): number
